
# Header
menu:
  Home: /
# Archives: /archives

# Content

# Sidebar

# display widgets at the bottom of index pages (pagination == 2)

# - category
# - tagcloud
# - archive

# widget behavior

# Miscellaneous
# google_analytics:
# gauges_analytics:
# favicon: /favicon.png
# twitter:
# google_plus:
# b_admins:
# fb_app_id:
