on:
  push:
    branches:    
      - master
    paths:
      - 'doc/_posts/en_us/**'
      - 'themes/**'
      - '!themes/momentum/source/lib/**'
  pull_request:
    branches:    
      - master
    paths:
      - 'doc/_posts/en_us/**'
      - 'themes/**'
      - '!themes/momentum/source/lib/**'
name: generate
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"
    - name: Set Env
      env: 
        GITHUB_ACCESS_TOKEN: ${{ secrets.www }} 
      run: |
        git config --global user.name 'yulhuang'
        git config --global user.email 'yulhuang@cisco.com'
        sed -i "s/GITHUB_ACCESS_TOKEN/$GITHUB_ACCESS_TOKEN/g" ./_config.yml
    - name: Hexo
      run: |
        npm i -g hexo-cli
        npm i -f
        hexo clean && hexo g && hexo d
